name: newsurv
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - numpy=1.24.2
  - matplotlib=3.7.1
  - lifelines=0.27.4
  - seaborn=0.12.2
  - ipykernel
  - yaml
  - openpyxl
  - ca-certificates
  - certifi
  - openssl
  - nextflow
  - pandas=1.5.3
  - autopep8
  - pyyaml
  - pytest
  - snakemake
  - anaconda::graphviz
